"""increase password_hash length to 255

Revision ID: 200c4b926944
Revises: 62acfac51251
Create Date: 2025-12-26 22:00:50.999532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200c4b926944'
down_revision = '62acfac51251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
